### ISSUE TITLE
[Bug] pueue 3.1.2 fails to build with rust 1.70

### ISSUE THREAD

**Issue by tranzystorek-io** [Nukesor/pueue#441]
Build error:

```
Compiling pueue v3.1.2 (/builddir/pueue-3.1.2/pueue)
error[E0170]: pattern binding `column` is named the same as one of the variants of the type `client::query::Rule`
  --> pueue/src/client/query/filters.rs:72:9
   |
72 |     let column = column.as_rule();
   |         ^^^^^^
   |
   = note: `#[deny(bindings_with_variant_name)]` on by default

error[E0170]: pattern binding `column` is named the same as one of the variants of the type `client::query::Rule`
  --> pueue/src/client/query/order_by.rs:72:9
   |
72 |     let column = column_keyword.into_inner().next().unwrap().as_rule();
   |         ^^^^^^

For more information about this error, try `rustc --explain E0170`.
error: could not compile `pueue` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by Nukesor** [comment]
Yep. This was already a think in `v1.69` and is fixed on `main`.
I'm planning on releasing 3.2 in the near future, but I'm currently on vacation for a few more days :)

**Comment by tranzystorek-io** [comment]
Ah, thank you, didn't want to interrupt your rest!
