### ISSUE TITLE
Fails to build with stable rustc 1.53.0

### ISSUE THREAD

**Issue by jirutka** [Nukesor/pueue#230]
```
$ cargo build --release --locked
...
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling async-global-executor v2.0.2
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`
````

It’s really a bad idea to depend on a beta version of some crate (`clap`) in a stable release.

**Additional context**
- Alpine Linux Edge
- pueue 1.0.1
